### ISSUE TITLE
sudo apt install docker-compose

### ISSUE THREAD

**Issue by ductnn** [vietanhphamnhu/setup-os#2]
https://github.com/vietanhphamnhu/setup-os/blob/e65f4ae6b9bdbcb629f7408fb95291fda60343fd/Setup.sh#L26

**Comment by anhpnv** [comment]
Updated
[sudo apt install docker-compose -y](https://github.com/vietanhphamnhu/setup-os/blob/f71f2af3851e834e8feb9aa3a6e5d61cf1602344/Setup.sh#L27)
